name: Unit Testing
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: ${{ env.JAVA_VERSION }}
      - name: Run Tests
        run: gradle test